/**
 * SNBT Tryout Pro — Bank Soal Tambahan Set 4 (questions_extra4.js)
 * 170 soal ekstra — semua baru, tidak ada yang sama dengan Set 1, 2, & 3
 * Distribusi: PU=30, PPU=20, PBM=20, PK=20, LBI=30, LBE=20, PM=30
 * Referensi: Pola soal UTBK SNBT 2023–2026
 * Digabung via getShuffledQuestions() bersama bank soal lainnya
 */

const QUESTION_BANK_EXTRA4 = {

  // ═══════════════════════════════════════════════════════
  // PU — PENALARAN UMUM (30 soal)
  // ═══════════════════════════════════════════════════════
  PU: [
    // --- Deret Angka ---
    { id:'PU-G01', question:'Deret: 2, 6, 12, 20, 30, __', options:['A. 40','B. 42','C. 44','D. 46','E. 48'], answer:'B', explanation:'Selisih: +4,+6,+8,+10,+12 → 30+12=42' },
    { id:'PU-G02', question:'Deret: 1, 3, 7, 13, 21, 31, __', options:['A. 41','B. 43','C. 44','D. 45','E. 48'], answer:'B', explanation:'Selisih: +2,+4,+6,+8,+10,+12 → 31+12=43' },
    { id:'PU-G03', question:'Deret: 5, 10, 20, 40, 80, __', options:['A. 100','B. 120','C. 140','D. 160','E. 180'], answer:'D', explanation:'Pola ×2. 80×2=160' },
    { id:'PU-G04', question:'Deret: 729, 243, 81, 27, __', options:['A. 6','B. 7','C. 8','D. 9','E. 3'], answer:'D', explanation:'Pola ÷3. 27÷3=9' },
    { id:'PU-G05', question:'Deret: 1, 2, 4, 7, 11, 16, __', options:['A. 20','B. 21','C. 22','D. 23','E. 24'], answer:'C', explanation:'Selisih: +1,+2,+3,+4,+5,+6 → 16+6=22' },
    { id:'PU-G06', question:'Deret huruf: Z, X, V, T, R, __', options:['A. O','B. P','C. Q','D. S','E. N'], answer:'B', explanation:'Mundur 2 huruf setiap suku: Z,X,V,T,R,P' },
    { id:'PU-G07', question:'Deret: 2, 3, 5, 8, 13, 21, __', options:['A. 28','B. 29','C. 33','D. 34','E. 35'], answer:'D', explanation:'Fibonacci: setiap suku = jumlah dua suku sebelumnya. 13+21=34' },
    { id:'PU-G08', question:'Deret: 1000, 500, 250, 125, __', options:['A. 60','B. 62.5','C. 63','D. 65','E. 70'], answer:'B', explanation:'Pola ÷2. 125÷2=62.5' },
    { id:'PU-G09', question:'Deret: 4, 9, 16, 25, 36, 49, __', options:['A. 56','B. 60','C. 63','D. 64','E. 66'], answer:'D', explanation:'Deret kuadrat: 2²,3²,4²,...,8²=64' },
    { id:'PU-G10', question:'Deret campuran: 2, A, 4, C, 6, E, 8, __', options:['A. F','B. G','C. H','D. I','E. J'], answer:'B', explanation:'Angka genap naik +2; huruf melompat 2 (A,C,E,G)' },

    // --- Analogi Verbal ---
    { id:'PU-G11', question:'PUISI : PENYAIR = PATUNG : ?', options:['A. Batu','B. Pemahat','C. Museum','D. Ukiran','E. Seniman'], answer:'B', explanation:'Puisi dibuat oleh Penyair; Patung dibuat oleh Pemahat' },
    { id:'PU-G12', question:'DOKTER : RUMAH SAKIT = GURU : ?', options:['A. Buku','B. Papan Tulis','C. Sekolah','D. Murid','E. Ujian'], answer:'C', explanation:'Dokter bertugas di Rumah Sakit; Guru bertugas di Sekolah' },
    { id:'PU-G13', question:'ELANG : TERBANG = IKAN : ?', options:['A. Berenang','B. Berlari','C. Melompat','D. Merayap','E. Menyelam'], answer:'A', explanation:'Elang bergerak dengan terbang; Ikan bergerak dengan berenang' },
    { id:'PU-G14', question:'KAMUS : KATA = ENSIKLOPEDIA : ?', options:['A. Ilmu','B. Pengetahuan','C. Topik','D. Teks','E. Artikel'], answer:'C', explanation:'Kamus berisi kata-kata; Ensiklopedia berisi topik-topik pengetahuan' },
    { id:'PU-G15', question:'API : PANAS = ES : ?', options:['A. Beku','B. Cair','C. Dingin','D. Putih','E. Air'], answer:'C', explanation:'Api identik dengan panas; Es identik dengan dingin' },
    { id:'PU-G16', question:'SINGA : MENGAUM = ULAR : ?', options:['A. Mendesis','B. Menggonggong','C. Mencicit','D. Meraung','E. Melengking'], answer:'A', explanation:'Singa mengeluarkan suara mengaum; Ular mengeluarkan suara mendesis' },
    { id:'PU-G17', question:'ASTRONOT : LUAR ANGKASA = ARKEOLOG : ?', options:['A. Museum','B. Laboratorium','C. Hutan','D. Situs Purbakala','E. Perpustakaan'], answer:'D', explanation:'Astronot bekerja di luar angkasa; Arkeolog bekerja di situs purbakala' },

    // --- Silogisme & Penalaran Logis ---
    { id:'PU-G18', question:'Semua mahasiswa harus mengerjakan skripsi. Andi adalah mahasiswa. Kesimpulan yang tepat adalah:', options:['A. Andi tidak perlu skripsi','B. Andi harus mengerjakan skripsi','C. Skripsi hanya untuk Andi','D. Semua mahasiswa bernama Andi','E. Andi bukan mahasiswa'], answer:'B', explanation:'Dari premis universal dan premis khusus, diperoleh: Andi harus mengerjakan skripsi' },
    { id:'PU-G19', question:'Tidak ada politisi yang jujur. Bagas adalah orang yang jujur. Maka:', options:['A. Bagas adalah politisi','B. Bagas mungkin politisi','C. Bagas bukan politisi','D. Semua jujur adalah Bagas','E. Politisi bisa jujur'], answer:'C', explanation:'Karena tidak ada politisi yang jujur, dan Bagas jujur, maka Bagas pasti bukan politisi' },
    { id:'PU-G20', question:'Jika hujan turun, maka jalanan basah. Jalanan tidak basah. Maka:', options:['A. Hujan turun','B. Hujan tidak turun','C. Cuaca cerah','D. Mungkin hujan','E. Jalanan kering karena angin'], answer:'B', explanation:'Modus Tollens: jika p→q, dan ¬q, maka ¬p. Jalanan tidak basah → hujan tidak turun' },
    { id:'PU-G21', question:'Semua buah tropis mengandung vitamin C. Mangga adalah buah tropis. Maka:', options:['A. Mangga tidak mengandung vitamin C','B. Vitamin C hanya ada di mangga','C. Mangga mengandung vitamin C','D. Semua vitamin C ada di buah tropis','E. Mangga mungkin buah tropis'], answer:'C', explanation:'Silogisme kategoris langsung: Mangga mengandung vitamin C' },
    { id:'PU-G22', question:'Pernyataan: "Jika seseorang rajin belajar, ia akan lulus ujian." Manakah yang PASTI SALAH berdasarkan pernyataan ini?', options:['A. Seseorang rajin belajar dan lulus','B. Seseorang tidak rajin dan tidak lulus','C. Seseorang rajin belajar tetapi tidak lulus','D. Seseorang tidak rajin dan lulus','E. Tidak ada yang pasti salah'], answer:'C', explanation:'Pernyataan bersifat implikasi: rajin → lulus. Kontradiksinya: rajin tetapi tidak lulus' },

    // --- Penalaran Analitis ---
    { id:'PU-G23', question:'Lima orang (A, B, C, D, E) duduk berurutan. A di sebelah kiri B. C di sebelah kanan D. E berada di tengah. Siapa yang paling kiri?', options:['A. A','B. B','C. C','D. D','E. E'], answer:'D', explanation:'Posisi dari kiri: D, C, E (tengah), A, B. D adalah paling kiri' },
    { id:'PU-G24', question:'Rani lebih tinggi dari Sari. Tini lebih pendek dari Rani. Umi lebih tinggi dari Rani. Siapakah yang paling tinggi?', options:['A. Rani','B. Sari','C. Tini','D. Umi','E. Tidak dapat ditentukan'], answer:'D', explanation:'Umi > Rani > Tini dan Umi > Rani > Sari. Umi paling tinggi' },
    { id:'PU-G25', question:'Sebuah persegi memiliki diagonal 10√2 cm. Luas persegi tersebut adalah:', options:['A. 50 cm²','B. 100 cm²','C. 150 cm²','D. 200 cm²','E. 250 cm²'], answer:'B', explanation:'Diagonal persegi = s√2. s√2=10√2 → s=10. Luas=10²=100 cm²' },
    { id:'PU-G26', question:'Jika p bernilai benar dan q bernilai salah, maka nilai kebenaran dari p ∨ q adalah:', options:['A. Benar','B. Salah','C. Tergantung','D. Tidak terdefinisi','E. Benar dan Salah'], answer:'A', explanation:'p ∨ q (atau) bernilai benar jika minimal satu bernilai benar. p=benar → p ∨ q = benar' },
    { id:'PU-G27', question:'Dari pernyataan "Semua reptil berdarah dingin" dan "Kadal adalah reptil", kesimpulannya adalah:', options:['A. Kadal bukan reptil','B. Ada reptil berdarah panas','C. Kadal berdarah dingin','D. Semua hewan berdarah dingin','E. Reptil bisa berdarah panas'], answer:'C', explanation:'Silogisme langsung: Kadal berdarah dingin' },
    { id:'PU-G28', question:'Negasi dari pernyataan "Semua siswa lulus ujian" adalah:', options:['A. Tidak ada siswa yang lulus','B. Beberapa siswa tidak lulus ujian','C. Semua siswa tidak lulus','D. Siswa tidak mengikuti ujian','E. Ada siswa yang lulus dan tidak lulus'], answer:'B', explanation:'Negasi dari "Semua A adalah B" adalah "Ada/beberapa A yang bukan B"' },
    { id:'PU-G29', question:'Deret gambar: segitiga, persegi, segilima, segienam, __ Berapa sisi bangun berikutnya?', options:['A. 6','B. 7','C. 8','D. 9','E. 10'], answer:'B', explanation:'Pola jumlah sisi: 3,4,5,6,7. Berikutnya adalah segi tujuh (7 sisi)' },
    { id:'PU-G30', question:'Lima tim (P,Q,R,S,T) bermain turnamen. P mengalahkan Q. R mengalahkan P. S kalah dari Q. T mengalahkan R. Tim terkuat adalah:', options:['A. P','B. Q','C. R','D. S','E. T'], answer:'E', explanation:'T > R > P > Q > S. Tim terkuat adalah T' },
  ],

  // ═══════════════════════════════════════════════════════
  // PPU — PENGETAHUAN & PEMAHAMAN UMUM (20 soal)
  // ═══════════════════════════════════════════════════════
  PPU: [
    { id:'PPU-G01', question:'Proses fotosintesis pada tumbuhan menghasilkan:', options:['A. CO₂ dan air','B. O₂ dan glukosa','C. N₂ dan protein','D. H₂O dan karbon','E. O₃ dan mineral'], answer:'B', explanation:'Fotosintesis: CO₂ + H₂O + cahaya → glukosa (C₆H₁₂O₆) + O₂' },
    { id:'PPU-G02', question:'Konstitusi tertulis Indonesia yang pertama kali berlaku adalah:', options:['A. UUD RIS 1949','B. UUD Sementara 1950','C. UUD 1945 (asli)','D. UUD 1945 Amandemen','E. Piagam Jakarta'], answer:'C', explanation:'UUD 1945 resmi berlaku sejak 18 Agustus 1945, sehari setelah proklamasi' },
    { id:'PPU-G03', question:'Organ tubuh manusia yang berfungsi menyaring darah adalah:', options:['A. Hati','B. Jantung','C. Paru-paru','D. Ginjal','E. Limpa'], answer:'D', explanation:'Ginjal berfungsi menyaring darah dan menghasilkan urine' },
    { id:'PPU-G04', question:'Revolusi Industri pertama kali terjadi di negara:', options:['A. Perancis','B. Amerika Serikat','C. Jerman','D. Inggris','E. Belanda'], answer:'D', explanation:'Revolusi Industri dimulai di Inggris sekitar abad ke-18 dengan penggunaan mesin uap' },
    { id:'PPU-G05', question:'Satuan dasar kecepatan dalam SI adalah:', options:['A. km/jam','B. m/s','C. cm/s','D. mil/jam','E. knot'], answer:'B', explanation:'Sistem Internasional (SI) menggunakan meter per sekon (m/s) sebagai satuan kecepatan' },
    { id:'PPU-G06', question:'Tokoh yang dikenal sebagai "Bapak Sosiologi" adalah:', options:['A. Karl Marx','B. Max Weber','C. Auguste Comte','D. Émile Durkheim','E. Herbert Spencer'], answer:'C', explanation:'Auguste Comte adalah orang pertama yang menggunakan istilah "sosiologi"' },
    { id:'PPU-G07', question:'Planet yang memiliki cincin paling terkenal di tata surya adalah:', options:['A. Jupiter','B. Uranus','C. Neptunus','D. Saturnus','E. Mars'], answer:'D', explanation:'Saturnus terkenal karena cincinnya yang besar dan jelas, tersusun dari es dan debu' },
    { id:'PPU-G08', question:'Perjanjian yang mengakhiri Perang Dunia I ditandatangani di:', options:['A. Paris','B. Berlin','C. Versailles','D. London','E. Wina'], answer:'C', explanation:'Perjanjian Versailles (1919) secara resmi mengakhiri Perang Dunia I' },
    { id:'PPU-G09', question:'Unsur kimia yang paling melimpah di kerak bumi adalah:', options:['A. Silikon','B. Aluminium','C. Oksigen','D. Besi','E. Kalsium'], answer:'C', explanation:'Oksigen merupakan unsur paling melimpah di kerak bumi (~46%)' },
    { id:'PPU-G10', question:'Prinsip dasar demokrasi Pancasila tercermin dalam sila ke-:', options:['A. Satu','B. Dua','C. Tiga','D. Empat','E. Lima'], answer:'D', explanation:'Sila keempat: "Kerakyatan yang Dipimpin oleh Hikmat Kebijaksanaan dalam Permusyawaratan/Perwakilan"' },
    { id:'PPU-G11', question:'Mahatma Gandhi dikenal sebagai pemimpin kemerdekaan negara:', options:['A. Pakistan','B. Bangladesh','C. Sri Lanka','D. India','E. Nepal'], answer:'D', explanation:'Mahatma Gandhi memimpin gerakan kemerdekaan India dari penjajahan Inggris' },
    { id:'PPU-G12', question:'Lapisan atmosfer yang berfungsi melindungi bumi dari sinar ultraviolet adalah:', options:['A. Troposfer','B. Stratosfer','C. Mesosfer','D. Termosfer','E. Eksosfer'], answer:'B', explanation:'Ozon terkonsentrasi di stratosfer dan menyerap sebagian besar sinar UV dari matahari' },
    { id:'PPU-G13', question:'Dalam sistem pencernaan, enzim amilase berfungsi untuk memecah:', options:['A. Protein','B. Lemak','C. Karbohidrat','D. Vitamin','E. Mineral'], answer:'C', explanation:'Amilase (dari air liur dan pankreas) memecah karbohidrat/amilum menjadi gula sederhana' },
    { id:'PPU-G14', question:'Peristiwa Reformasi 1998 di Indonesia ditandai dengan mundurnya presiden:', options:['A. Sukarno','B. Soeharto','C. B.J. Habibie','D. Abdurrahman Wahid','E. Megawati'], answer:'B', explanation:'Presiden Soeharto mengundurkan diri pada 21 Mei 1998 setelah tekanan reformasi besar-besaran' },
    { id:'PPU-G15', question:'Alat musik angklung berasal dari daerah:', options:['A. Jawa Tengah','B. Bali','C. Sulawesi','D. Jawa Barat','E. Sumatera Barat'], answer:'D', explanation:'Angklung adalah alat musik tradisional khas Jawa Barat (Sunda), terbuat dari bambu' },
    { id:'PPU-G16', question:'Hukum Newton I menyatakan bahwa benda akan tetap diam atau bergerak lurus beraturan jika:', options:['A. Ada gaya yang bekerja','B. Tidak ada resultan gaya','C. Massanya sangat besar','D. Kecepatan konstan','E. Berada di ruang hampa'], answer:'B', explanation:'Hukum I Newton (inersia): benda bergerak lurus atau diam jika resultan gaya = 0' },
    { id:'PPU-G17', question:'Simbol kimia untuk emas adalah:', options:['A. Ag','B. Fe','C. Cu','D. Au','E. Pt'], answer:'D', explanation:'Au berasal dari kata Latin "Aurum" yang berarti emas' },
    { id:'PPU-G18', question:'Teori evolusi Charles Darwin didasarkan pada konsep:', options:['A. Generatio spontanea','B. Seleksi alam','C. Mutasi buatan','D. Pewarisan acquired traits','E. Biogenesis'], answer:'B', explanation:'Darwin mengemukakan bahwa evolusi terjadi melalui seleksi alam (natural selection)' },
    { id:'PPU-G19', question:'Lembaga yang berwenang menguji undang-undang terhadap UUD 1945 di Indonesia adalah:', options:['A. Mahkamah Agung','B. Dewan Perwakilan Rakyat','C. Mahkamah Konstitusi','D. Komisi Yudisial','E. Kejaksaan Agung'], answer:'C', explanation:'Mahkamah Konstitusi berwenang melakukan judicial review UU terhadap UUD 1945' },
    { id:'PPU-G20', question:'Teks Proklamasi Kemerdekaan Indonesia dikumandangkan pada tanggal:', options:['A. 1 Juni 1945','B. 16 Agustus 1945','C. 17 Agustus 1945','D. 18 Agustus 1945','E. 20 Agustus 1945'], answer:'C', explanation:'Proklamasi Kemerdekaan RI dibacakan Soekarno-Hatta pada 17 Agustus 1945 pukul 10.00 WIB' },
  ],

  // ═══════════════════════════════════════════════════════
  // PBM — PEMAHAMAN BACAAN & MENULIS (20 soal)
  // ═══════════════════════════════════════════════════════
  PBM: [
    // Bacaan 1: Perubahan Iklim
    { id:'PBM-G01', question:'Bacalah teks berikut:\n"Perubahan iklim merupakan salah satu tantangan terbesar abad ke-21. Kenaikan suhu rata-rata bumi menyebabkan mencairnya es di kutub, naiknya permukaan air laut, dan meningkatnya frekuensi bencana alam. Para ilmuwan sepakat bahwa aktivitas manusia—terutama pembakaran bahan bakar fosil—menjadi penyebab utama fenomena ini."\n\nIde pokok paragraf di atas adalah:', options:['A. Bencana alam akibat perubahan iklim','B. Perubahan iklim sebagai tantangan besar','C. Pembakaran bahan bakar fosil','D. Naiknya permukaan air laut','E. Mencairnya es di kutub'], answer:'B', explanation:'Kalimat pertama menyatakan ide pokok: perubahan iklim sebagai tantangan terbesar' },
    { id:'PBM-G02', question:'Berdasarkan teks tentang perubahan iklim di soal sebelumnya, apa yang disepakati para ilmuwan?', options:['A. Bencana alam tidak dapat dicegah','B. Suhu bumi tidak berubah','C. Aktivitas manusia menjadi penyebab utama perubahan iklim','D. Es di kutub tidak mencair','E. Permukaan laut tidak naik'], answer:'C', explanation:'Kalimat terakhir teks menegaskan bahwa para ilmuwan sepakat aktivitas manusia menjadi penyebab utama' },
    { id:'PBM-G03', question:'Kata "fenomena" dalam teks tentang perubahan iklim memiliki makna:', options:['A. Bencana','B. Kejadian atau gejala yang dapat diamati','C. Teori ilmiah','D. Pendapat ahli','E. Peraturan alam'], answer:'B', explanation:'Fenomena berarti kejadian, gejala, atau peristiwa yang dapat diamati atau dirasakan' },

    // Bacaan 2: Teknologi AI
    { id:'PBM-G04', question:'Bacalah teks berikut:\n"Kecerdasan buatan (Artificial Intelligence/AI) kini merambah hampir semua sektor kehidupan. Dari dunia medis, pendidikan, hingga hiburan, AI hadir menawarkan efisiensi dan kemudahan. Namun, di sisi lain, kekhawatiran tentang penggantian tenaga kerja manusia dan isu privasi data terus menjadi perdebatan."\n\nTeks di atas bertujuan:', options:['A. Melarang penggunaan AI','B. Mempromosikan AI','C. Menyajikan gambaran dua sisi tentang AI','D. Menjelaskan cara kerja AI','E. Mengkritik AI secara keras'], answer:'C', explanation:'Teks menyajikan sisi positif (efisiensi) dan negatif (kekhawatiran) AI secara berimbang' },
    { id:'PBM-G05', question:'Sinonim kata "merambah" dalam konteks teks AI adalah:', options:['A. Mundur','B. Masuk dan menyebar ke','C. Meninggalkan','D. Menguasai secara paksa','E. Mengabaikan'], answer:'B', explanation:'"Merambah" berarti menjelajahi atau menyebar masuk ke suatu wilayah/bidang' },
    { id:'PBM-G06', question:'Antonim kata "efisiensi" adalah:', options:['A. Produktivitas','B. Kecepatan','C. Pemborosan','D. Kualitas','E. Kemudahan'], answer:'C', explanation:'Efisiensi = penggunaan sumber daya secara hemat dan tepat; antonimnya adalah pemborosan' },

    // Penulisan & Ejaan
    { id:'PBM-G07', question:'Kalimat manakah yang menggunakan tanda baca paling tepat?', options:['A. Ibu membeli: sayur, buah dan daging.','B. Ibu membeli sayur, buah, dan daging.','C. Ibu membeli sayur; buah dan daging.','D. Ibu membeli sayur buah, dan daging.','E. Ibu membeli, sayur buah dan daging.'], answer:'B', explanation:'Dalam perincian lebih dari dua unsur, gunakan koma di antara setiap unsur termasuk sebelum "dan"' },
    { id:'PBM-G08', question:'Penulisan kata serapan yang BENAR adalah:', options:['A. nasehat','B. analisa','C. praktek','D. jadwal','E. ijazah'], answer:'D', explanation:'Penulisan baku: nasihat, analisis, praktik, jadwal, ijazah. "Jadwal" sudah baku' },
    { id:'PBM-G09', question:'Kalimat efektif yang paling tepat adalah:', options:['A. Karena hujan lebat, maka jalan menjadi banjir.','B. Hujan lebat menyebabkan banjir di jalan.','C. Hujan yang lebat sekali menyebabkan jalan yang banjir.','D. Dikarenakan hujan yang lebat, maka terjadilah banjir.','E. Banjir terjadi disebabkan karena hujan lebat.'], answer:'B', explanation:'Kalimat B paling efektif: tidak ada kata mubazir, struktur S-P-O jelas' },
    { id:'PBM-G10', question:'Kata "di" yang penulisannya DIPISAH dari kata berikutnya adalah:', options:['A. dibeli','B. dimakan','C. di rumah','D. diambil','E. ditaruh'], answer:'C', explanation:'"Di" sebagai kata depan (preposisi) ditulis terpisah; "di-" sebagai awalan ditulis serangkai. "Di rumah" = preposisi' },
    { id:'PBM-G11', question:'Paragraf yang baik harus memiliki satu gagasan pokok. Gagasan pokok yang tersurat (tertulis langsung) disebut:', options:['A. Implisit','B. Tersurat','C. Kalimat utama','D. Kalimat penjelas','E. Simpulan'], answer:'C', explanation:'Gagasan pokok yang tersurat ditemukan dalam kalimat utama/topik dalam paragraf' },
    { id:'PBM-G12', question:'Kata hubung yang menyatakan pertentangan adalah:', options:['A. dan','B. serta','C. bahkan','D. namun','E. lalu'], answer:'D', explanation:'"Namun" adalah konjungsi yang menunjukkan pertentangan. Lainnya: dan/serta (penambahan), bahkan (penguatan), lalu (urutan)' },

    // Bacaan 3: Sosial Budaya
    { id:'PBM-G13', question:'Bacalah teks:\n"Budaya literasi di Indonesia masih perlu ditingkatkan. Data UNESCO menunjukkan minat baca Indonesia masih rendah dibanding negara-negara lain. Padahal, kemampuan membaca kritis merupakan fondasi utama dalam membangun sumber daya manusia yang kompetitif."\n\nKesimpulan yang dapat ditarik dari teks tersebut adalah:', options:['A. Indonesia tidak memiliki budaya membaca','B. UNESCO melarang warga Indonesia membaca','C. Meningkatkan literasi penting untuk daya saing SDM Indonesia','D. SDM Indonesia sudah kompetitif','E. Membaca hanya penting untuk pelajar'], answer:'C', explanation:'Teks menghubungkan rendahnya literasi dengan kebutuhan SDM kompetitif, sehingga peningkatan literasi adalah solusinya' },
    { id:'PBM-G14', question:'Kata "fondasi" dalam teks literasi memiliki makna:', options:['A. Hambatan','B. Dasar/landasan','C. Puncak','D. Tujuan','E. Hasil'], answer:'B', explanation:'Fondasi berarti dasar atau landasan yang mendukung sesuatu' },
    { id:'PBM-G15', question:'Kata "kompetitif" dalam teks literasi berarti:', options:['A. Lemah','B. Kooperatif','C. Berdaya saing','D. Kreatif','E. Produktif'], answer:'C', explanation:'Kompetitif = mampu bersaing; berasal dari kata "kompetisi" (persaingan)' },

    // Pemahaman Struktur Kalimat
    { id:'PBM-G16', question:'Kalimat "Para siswa mengerjakan soal ujian dengan tekun" memiliki struktur:', options:['A. S-P-O','B. S-P-K','C. S-P-O-K','D. S-K-P-O','E. K-S-P-O'], answer:'C', explanation:'Para siswa (S) + mengerjakan (P) + soal ujian (O) + dengan tekun (K/cara)' },
    { id:'PBM-G17', question:'Manakah kalimat yang menggunakan kalimat pasif dengan benar?', options:['A. Buku itu dibaca oleh Rena kemarin','B. Rena membaca buku itu kemarin','C. Buku itu membaca Rena kemarin','D. Membaca buku itu Rena kemarin','E. Rena dibaca buku itu kemarin'], answer:'A', explanation:'Kalimat pasif: subjek dikenai pekerjaan, menggunakan "di-" + "oleh". Buku (S) + dibaca (P pasif) + oleh Rena (pelaku) + kemarin (K)' },
    { id:'PBM-G18', question:'Wacana yang bertujuan memengaruhi pembaca untuk setuju dengan pendapat penulis disebut:', options:['A. Narasi','B. Deskripsi','C. Eksposisi','D. Argumentasi/Persuasi','E. Prosedur'], answer:'D', explanation:'Teks argumentasi/persuasi bertujuan meyakinkan atau memengaruhi pembaca' },
    { id:'PBM-G19', question:'Manakah yang merupakan kalimat majemuk setara?', options:['A. Ia tidur karena lelah','B. Meskipun hujan, ia tetap berangkat','C. Ia belajar dan adiknya bermain','D. Ia berangkat setelah makan','E. Ketika bel berbunyi, siswa masuk kelas'], answer:'C', explanation:'Kalimat majemuk setara: dua klausa dihubungkan konjungsi setara "dan", kedudukan sejajar' },
    { id:'PBM-G20', question:'Paragraf induktif adalah paragraf yang:', options:['A. Kalimat utama di awal','B. Kalimat utama di tengah','C. Kalimat utama di akhir','D. Tidak memiliki kalimat utama','E. Kalimat utama di awal dan akhir'], answer:'C', explanation:'Paragraf induktif: dimulai dari hal-hal khusus menuju simpulan/kalimat utama di akhir' },
  ],

  // ═══════════════════════════════════════════════════════
  // PK — PENGETAHUAN KUANTITATIF (20 soal)
  // ═══════════════════════════════════════════════════════
  PK: [
    { id:'PK-G01', question:'Jika 3x + 7 = 22, maka nilai x adalah:', options:['A. 3','B. 4','C. 5','D. 6','E. 7'], answer:'C', explanation:'3x = 22 - 7 = 15 → x = 5' },
    { id:'PK-G02', question:'Berapakah 15% dari 240?', options:['A. 30','B. 32','C. 34','D. 36','E. 38'], answer:'D', explanation:'15% × 240 = 0,15 × 240 = 36' },
    { id:'PK-G03', question:'Sebuah lingkaran memiliki jari-jari 7 cm. Kelilingnya (π = 22/7) adalah:', options:['A. 42 cm','B. 44 cm','C. 46 cm','D. 48 cm','E. 50 cm'], answer:'B', explanation:'K = 2πr = 2 × (22/7) × 7 = 44 cm' },
    { id:'PK-G04', question:'Rata-rata dari 8, 12, 15, 19, 16 adalah:', options:['A. 13','B. 14','C. 15','D. 16','E. 17'], answer:'B', explanation:'Jumlah = 8+12+15+19+16 = 70. Rata-rata = 70/5 = 14' },
    { id:'PK-G05', question:'Jika harga barang naik 20% dari Rp50.000, harga baru adalah:', options:['A. Rp55.000','B. Rp58.000','C. Rp60.000','D. Rp62.000','E. Rp65.000'], answer:'C', explanation:'Kenaikan = 20% × 50.000 = 10.000. Harga baru = 50.000 + 10.000 = 60.000' },
    { id:'PK-G06', question:'Volume kubus dengan rusuk 5 cm adalah:', options:['A. 75 cm³','B. 100 cm³','C. 125 cm³','D. 150 cm³','E. 175 cm³'], answer:'C', explanation:'V = s³ = 5³ = 125 cm³' },
    { id:'PK-G07', question:'Diketahui data: 4, 6, 8, 6, 10, 6, 12. Nilai modus adalah:', options:['A. 4','B. 6','C. 8','D. 10','E. 12'], answer:'B', explanation:'Angka 6 muncul 3 kali (paling sering) → Modus = 6' },
    { id:'PK-G08', question:'Jika 2/3 dari suatu bilangan adalah 18, bilangan tersebut adalah:', options:['A. 24','B. 27','C. 30','D. 33','E. 36'], answer:'B', explanation:'(2/3)x = 18 → x = 18 × (3/2) = 27' },
    { id:'PK-G09', question:'Seorang penjahit dapat menyelesaikan 4 baju dalam 6 jam. Berapa jam untuk menyelesaikan 10 baju?', options:['A. 12','B. 13','C. 14','D. 15','E. 16'], answer:'D', explanation:'Laju: 4 baju/6 jam = 2 baju/3 jam. Waktu 10 baju = 10 × (3/2) = 15 jam' },
    { id:'PK-G10', question:'Jika p = 3 dan q = −2, nilai 2p² − 3q adalah:', options:['A. 10','B. 12','C. 14','D. 16','E. 24'], answer:'E', explanation:'2(3)² − 3(−2) = 2(9) + 6 = 18 + 6 = 24' },
    { id:'PK-G11', question:'Sebuah kereta berangkat pukul 07.30 dan tiba pukul 11.15. Lama perjalanan adalah:', options:['A. 3 jam 30 menit','B. 3 jam 45 menit','C. 4 jam','D. 4 jam 15 menit','E. 3 jam 15 menit'], answer:'B', explanation:'Dari 07.30 ke 11.15 = 3 jam 45 menit' },
    { id:'PK-G12', question:'FPB (Faktor Persekutuan Terbesar) dari 36 dan 48 adalah:', options:['A. 6','B. 9','C. 12','D. 18','E. 24'], answer:'C', explanation:'36 = 2²×3²; 48 = 2⁴×3. FPB = 2²×3 = 12' },
    { id:'PK-G13', question:'Sebuah segitiga siku-siku memiliki dua sisi siku-siku 6 cm dan 8 cm. Panjang hipotenusanya adalah:', options:['A. 7 cm','B. 9 cm','C. 10 cm','D. 11 cm','E. 12 cm'], answer:'C', explanation:'c = √(6²+8²) = √(36+64) = √100 = 10 cm (Teorema Pythagoras)' },
    { id:'PK-G14', question:'Jika 5! (5 faktorial) = 120, maka 6! adalah:', options:['A. 600','B. 660','C. 700','D. 720','E. 750'], answer:'D', explanation:'6! = 6 × 5! = 6 × 120 = 720' },
    { id:'PK-G15', question:'Dua bilangan memiliki selisih 14 dan jumlah 46. Bilangan terbesar adalah:', options:['A. 25','B. 28','C. 30','D. 32','E. 35'], answer:'C', explanation:'x + y = 46 dan x − y = 14. 2x = 60 → x = 30 (terbesar)' },
    { id:'PK-G16', question:'Persentase 45 dari 180 adalah:', options:['A. 20%','B. 25%','C. 28%','D. 30%','E. 35%'], answer:'B', explanation:'(45/180) × 100% = 25%' },
    { id:'PK-G17', question:'Dari 10 siswa, 6 menyukai matematika, 5 menyukai IPA, 3 menyukai keduanya. Berapa yang tidak menyukai keduanya?', options:['A. 0','B. 1','C. 2','D. 3','E. 4'], answer:'C', explanation:'|M∪I| = 6+5−3 = 8. Tidak menyukai keduanya = 10−8 = 2' },
    { id:'PK-G18', question:'Barisan aritmetika: 5, 11, 17, 23, ... Suku ke-8 adalah:', options:['A. 43','B. 45','C. 47','D. 49','E. 51'], answer:'C', explanation:'a=5, b=6. U₈ = 5 + (8−1)×6 = 5+42 = 47' },
    { id:'PK-G19', question:'Sebuah toko memberikan diskon 30% untuk harga Rp200.000. Harga setelah diskon adalah:', options:['A. Rp120.000','B. Rp130.000','C. Rp140.000','D. Rp150.000','E. Rp160.000'], answer:'C', explanation:'Diskon = 30% × 200.000 = 60.000. Harga akhir = 200.000 − 60.000 = 140.000' },
    { id:'PK-G20', question:'Jika log 2 = 0,301 dan log 5 = 0,699, maka log 50 adalah:', options:['A. 1,301','B. 1,500','C. 1,699','D. 1,857','E. 2,000'], answer:'C', explanation:'log 50 = log(100/2) = log 100 − log 2 = 2 − 0,301 = 1,699' },
  ],

  // ═══════════════════════════════════════════════════════
  // LBI — LITERASI BAHASA INDONESIA (30 soal)
  // ═══════════════════════════════════════════════════════
  LBI: [
    // Teks 1: Ketahanan Pangan
    { id:'LBI-G01', question:'Bacalah teks berikut:\n"Indonesia sebagai negara agraris memiliki potensi besar dalam sektor pertanian. Namun, alih fungsi lahan pertanian menjadi kawasan industri dan permukiman terus mengancam ketahanan pangan nasional. Menurut data Kementerian Pertanian, luas lahan sawah berkurang sekitar 150.000 hektare per tahun. Jika tren ini tidak dikendalikan, Indonesia berpotensi mengalami krisis pangan dalam dua dekade mendatang."\n\nGagasan utama teks tersebut adalah:', options:['A. Indonesia adalah negara agraris','B. Ancaman alih fungsi lahan terhadap ketahanan pangan Indonesia','C. Data Kementerian Pertanian tentang sawah','D. Krisis pangan akan terjadi dua dekade lagi','E. Indonesia kehilangan 150.000 hektare sawah per tahun'], answer:'B', explanation:'Teks berpusat pada ancaman alih fungsi lahan terhadap ketahanan pangan, yang merupakan masalah utama yang dibahas' },
    { id:'LBI-G02', question:'Berdasarkan teks ketahanan pangan, apa dampak dari alih fungsi lahan pertanian?', options:['A. Meningkatnya produksi pangan','B. Berkurangnya kawasan industri','C. Potensi krisis pangan nasional','D. Meningkatnya populasi petani','E. Bertambahnya luas sawah'], answer:'C', explanation:'Paragraf terakhir menyebutkan bahwa jika tren alih fungsi lahan tidak dikendalikan, berpotensi menimbulkan krisis pangan' },
    { id:'LBI-G03', question:'Kata "agraris" dalam teks ketahanan pangan berarti:', options:['A. Berbasis industri','B. Berbasis pertanian/ladang','C. Berbasis kelautan','D. Berbasis perdagangan','E. Berbasis teknologi'], answer:'B', explanation:'"Agraris" berkaitan dengan pertanian atau tanah pertanian' },
    { id:'LBI-G04', question:'Jenis paragraf dalam teks ketahanan pangan adalah:', options:['A. Narasi','B. Deskripsi','C. Eksposisi analitis','D. Persuasi','E. Rekreasi'], answer:'C', explanation:'Teks memaparkan fakta, data, dan analisis tentang masalah lahan pertanian → eksposisi analitis' },

    // Teks 2: Pendidikan
    { id:'LBI-G05', question:'Bacalah teks:\n"Program Merdeka Belajar yang diluncurkan Kemendikbudristek bertujuan memberikan fleksibilitas kepada sekolah dan guru dalam menentukan kurikulum. Konsep ini menggeser paradigma pendidikan dari yang berpusat pada hafalan menuju pembelajaran berbasis kompetensi. Siswa diharapkan mampu berpikir kritis, kreatif, dan kolaboratif."\n\nTujuan Program Merdeka Belajar berdasarkan teks adalah:', options:['A. Menghapus hafalan sepenuhnya','B. Meningkatkan nilai ujian nasional','C. Memberi fleksibilitas dalam kurikulum dan mendorong kompetensi','D. Mengurangi jam pelajaran','E. Mengganti semua guru dengan teknologi'], answer:'C', explanation:'Paragraf pertama menyatakan tujuan: fleksibilitas kurikulum; paragraf selanjutnya menjelaskan perubahan paradigma ke kompetensi' },
    { id:'LBI-G06', question:'Kata "paradigma" dalam teks Merdeka Belajar bermakna:', options:['A. Metode belajar','B. Kerangka berpikir/cara pandang','C. Kurikulum sekolah','D. Tujuan pendidikan','E. Hasil belajar'], answer:'B', explanation:'"Paradigma" berarti kerangka berpikir, sudut pandang, atau cara memahami sesuatu' },
    { id:'LBI-G07', question:'Keterampilan abad 21 yang disebutkan dalam teks Merdeka Belajar adalah:', options:['A. Menghafal, cepat, dan akurat','B. Kritis, kreatif, dan kolaboratif','C. Rajin, disiplin, dan jujur','D. Teknologi, sains, dan seni','E. Komunikasi, komputer, dan akuntansi'], answer:'B', explanation:'Kalimat terakhir teks menyebutkan: berpikir kritis, kreatif, dan kolaboratif' },

    // Teks 3: Lingkungan Hidup
    { id:'LBI-G08', question:'Bacalah teks:\n"Sampah plastik telah menjadi ancaman serius bagi ekosistem laut Indonesia. Setiap tahun, jutaan ton plastik berakhir di lautan dan merusak habitat berbagai biota laut. Mikroplastik yang terbentuk dari degradasi plastik bahkan telah ditemukan dalam tubuh ikan konsumsi, yang mengancam rantai makanan manusia. Tanpa tindakan konkret, kerusakan ekosistem laut akan semakin parah."\n\nSimpulan yang paling tepat dari teks tersebut adalah:', options:['A. Ikan di Indonesia tidak boleh dikonsumsi','B. Plastik tidak bisa terurai di laut','C. Sampah plastik mengancam ekosistem laut dan kesehatan manusia','D. Pemerintah harus melarang penggunaan plastik','E. Mikroplastik hanya ada di lautan dalam'], answer:'C', explanation:'Teks membahas dampak plastik terhadap ekosistem laut (biota) dan manusia (rantai makanan), jadi simpulan paling tepat adalah C' },
    { id:'LBI-G09', question:'Kata "konkret" dalam teks sampah plastik berarti:', options:['A. Abstrak','B. Rencana sementara','C. Nyata dan dapat dilaksanakan','D. Teoritis','E. Bersifat perkiraan'], answer:'C', explanation:'"Konkret" berarti nyata, berwujud, dan dapat diimplementasikan' },
    { id:'LBI-G10', question:'Pernyataan manakah yang TIDAK SESUAI dengan teks sampah plastik?', options:['A. Plastik merusak habitat biota laut','B. Mikroplastik ditemukan dalam ikan konsumsi','C. Plastik mengancam rantai makanan manusia','D. Pemerintah telah berhasil mengatasi masalah plastik','E. Jutaan ton plastik berakhir di lautan setiap tahun'], answer:'D', explanation:'Teks tidak menyebutkan keberhasilan pemerintah; justru menyebut kerusakan akan semakin parah tanpa tindakan' },

    // Teks 4: Kesehatan
    { id:'LBI-G11', question:'Bacalah teks:\n"Gaya hidup sedentari—yakni kurang gerak dan banyak duduk—kini menjadi masalah kesehatan global. Penelitian menunjukkan bahwa duduk lebih dari 8 jam per hari meningkatkan risiko penyakit jantung, diabetes tipe 2, dan gangguan metabolisme. Aktivitas fisik minimal 30 menit sehari terbukti secara klinis mampu mengurangi risiko tersebut."\n\nMakna kata "sedentari" berdasarkan konteks teks adalah:', options:['A. Aktif bergerak','B. Sering berolahraga','C. Kurang bergerak dan banyak duduk','D. Pola makan tidak teratur','E. Tidur berlebihan'], answer:'C', explanation:'Teks mendefinisikan "sedentari" secara eksplisit: kurang gerak dan banyak duduk' },
    { id:'LBI-G12', question:'Menurut teks gaya hidup sedentari, berapa durasi aktivitas fisik minimal yang direkomendasikan per hari?', options:['A. 15 menit','B. 20 menit','C. 30 menit','D. 45 menit','E. 60 menit'], answer:'C', explanation:'Kalimat terakhir teks menyebutkan: "Aktivitas fisik minimal 30 menit sehari..."' },
    { id:'LBI-G13', question:'Penyakit yang disebutkan sebagai risiko gaya hidup sedentari adalah:', options:['A. Asma, migren, dan anemia','B. Jantung, diabetes tipe 2, dan gangguan metabolisme','C. Kanker, stroke, dan osteoporosis','D. TBC, malaria, dan demam berdarah','E. Hipertensi, insomnia, dan alergi'], answer:'B', explanation:'Teks secara eksplisit menyebut: penyakit jantung, diabetes tipe 2, dan gangguan metabolisme' },

    // Teks 5: Ekonomi Digital
    { id:'LBI-G14', question:'Bacalah teks:\n"Ekonomi digital Indonesia tumbuh pesat dengan valuasi ekosistem digital mencapai $77 miliar pada 2022 dan diproyeksikan melampaui $130 miliar pada 2025. Pertumbuhan ini didorong oleh penetrasi internet yang tinggi dan ledakan pengguna e-commerce. Namun, kesenjangan digital antara kota dan desa masih menjadi hambatan pemerataan manfaat ekonomi digital."\n\nPada teks ekonomi digital, hambatan pemerataan manfaat disebutkan adalah:', options:['A. Kurangnya startup','B. Rendahnya valuasi ekosistem','C. Kesenjangan digital antara kota dan desa','D. Minimnya pengguna e-commerce','E. Lambatnya pertumbuhan internet'], answer:'C', explanation:'Kalimat terakhir teks menyebutkan "kesenjangan digital antara kota dan desa" sebagai hambatan pemerataan' },
    { id:'LBI-G15', question:'Kata "valuasi" dalam teks ekonomi digital berarti:', options:['A. Pertumbuhan','B. Penilaian/estimasi nilai','C. Pendapatan bersih','D. Jumlah pengguna','E. Investasi asing'], answer:'B', explanation:'"Valuasi" adalah proses penilaian atau estimasi nilai ekonomi suatu bisnis atau aset' },

    // Soal Tata Bahasa & Kosakata
    { id:'LBI-G16', question:'Kalimat yang menggunakan kata baku dengan benar adalah:', options:['A. Dia aktip dalam kegiatan sosial','B. Kita harus saling menghormati antar sesama','C. Proyek ini sudah selesai dikerjakan','D. Mereka sedang berkumpul di komplek perumahan','E. Ia mendapat beasiswa dari yayasan filantropi'], answer:'E', explanation:'Pilihan A (aktip→aktif), B (antar sesama→sesama), C (tidak salah tapi kurang tepat), D (komplek→kompleks). E menggunakan kata-kata yang baku' },
    { id:'LBI-G17', question:'Peribahasa "Bagai air di daun talas" bermakna:', options:['A. Sangat setia','B. Tidak tetap pendirian / mudah berubah','C. Sangat bersih','D. Sangat cepat bergerak','E. Sangat jernih'], answer:'B', explanation:'Air di daun talas mudah bergulir dan tidak menetap, melambangkan orang yang tidak tetap pendirian' },
    { id:'LBI-G18', question:'Kata "ambigu" memiliki makna:', options:['A. Bermakna tunggal','B. Bermakna ganda/dapat ditafsirkan lebih dari satu cara','C. Tidak bermakna','D. Bermakna negatif','E. Sangat jelas maknanya'], answer:'B', explanation:'"Ambigu" berarti memiliki makna ganda atau dapat diinterpretasi lebih dari satu cara' },
    { id:'LBI-G19', question:'Kalimat "Hasil panen petani itu sangat banyak sekali" mengandung kesalahan berupa:', options:['A. Kesalahan ejaan','B. Pemborosan kata (pleonasme)','C. Kesalahan tanda baca','D. Kesalahan struktur kalimat','E. Penggunaan kata asing yang tidak tepat'], answer:'B', explanation:'"Sangat banyak sekali" adalah pleonasme (berlebihan): cukup "sangat banyak" atau "banyak sekali"' },
    { id:'LBI-G20', question:'Makna denotasi kata "bunga" adalah:', options:['A. Keindahan','B. Kelembutan','C. Organ reproduksi tumbuhan','D. Sesuatu yang indah','E. Ungkapan perasaan'], answer:'C', explanation:'Makna denotasi adalah makna sebenarnya/lugas: bunga = organ reproduksi tumbuhan. Makna konotasi = keindahan, kelembutan, dll.' },

    // Teks 6: Ilmu Pengetahuan
    { id:'LBI-G21', question:'Bacalah teks:\n"Gravitasi adalah gaya tarik-menarik antara dua benda yang memiliki massa. Semakin besar massa suatu benda dan semakin dekat jaraknya, semakin besar pula gaya gravitasinya. Isaac Newton merumuskan hukum gravitasi universal ini pada abad ke-17 setelah mengamati kejatuhan sebuah apel."\n\nHukum yang dirumuskan Newton adalah tentang:', options:['A. Gerak benda di ruang hampa','B. Hubungan antara massa dan kecepatan','C. Gaya tarik-menarik antara benda bermassa','D. Kecepatan cahaya di alam semesta','E. Tekanan udara di atmosfer'], answer:'C', explanation:'Teks secara jelas menyebutkan: "gaya tarik-menarik antara dua benda yang memiliki massa"' },
    { id:'LBI-G22', question:'Berdasarkan teks gravitasi, faktor yang memengaruhi besarnya gaya gravitasi adalah:', options:['A. Warna dan bentuk benda','B. Suhu dan tekanan udara','C. Massa dan jarak antara dua benda','D. Kecepatan dan arah gerak benda','E. Waktu dan tempat benda berada'], answer:'C', explanation:'Teks menyebutkan: "Semakin besar massa suatu benda dan semakin dekat jaraknya, semakin besar gaya gravitasinya"' },

    // Pemahaman Wacana Singkat
    { id:'LBI-G23', question:'Urutan penulisan laporan ilmiah yang benar adalah:', options:['A. Hasil, Pendahuluan, Metode, Simpulan','B. Pendahuluan, Metode, Hasil, Pembahasan, Simpulan','C. Simpulan, Metode, Hasil, Pendahuluan','D. Pembahasan, Simpulan, Pendahuluan, Metode','E. Metode, Pendahuluan, Hasil, Simpulan'], answer:'B', explanation:'Struktur laporan ilmiah standar: Pendahuluan → Metode → Hasil → Pembahasan → Simpulan' },
    { id:'LBI-G24', question:'Kata "anteseden" dalam linguistik mengacu pada:', options:['A. Kata yang dirujuk oleh kata ganti','B. Kata sifat','C. Kata kerja transitif','D. Kalimat penjelas','E. Konjungsi penghubung'], answer:'A', explanation:'"Anteseden" adalah kata atau kelompok kata yang dirujuk/digantikan oleh kata ganti (pronomina)' },
    { id:'LBI-G25', question:'Kata "sinergi" berarti:', options:['A. Pertentangan antarpihak','B. Kerja sama yang menghasilkan hasil lebih besar dari jumlah bagiannya','C. Persaingan sehat','D. Pembagian tugas','E. Negosiasi antardua pihak'], answer:'B', explanation:'"Sinergi" adalah kerja sama dua atau lebih pihak yang menghasilkan dampak lebih besar dari hasil masing-masing secara terpisah' },
    { id:'LBI-G26', question:'Bacalah teks:\n"Revolusi digital membawa perubahan mendasar dalam cara manusia berkomunikasi, bekerja, dan belajar. Jarak dan waktu bukan lagi hambatan utama. Namun, kemudahan akses informasi juga membuka peluang bagi penyebaran hoaks dan disinformasi yang membahayakan kohesi sosial."\n\nKata "disinformasi" dalam teks bermakna:', options:['A. Informasi yang lengkap','B. Informasi yang benar dan terverifikasi','C. Penyebaran informasi yang sengaja keliru untuk menyesatkan','D. Informasi yang tidak relevan','E. Informasi digital'], answer:'C', explanation:'"Disinformasi" adalah informasi palsu yang disebarkan dengan sengaja untuk menyesatkan' },
    { id:'LBI-G27', question:'Manakah penulisan judul buku yang sesuai kaidah EYD?', options:['A. panduan belajar bahasa indonesia','B. Panduan Belajar Bahasa Indonesia','C. PANDUAN BELAJAR BAHASA INDONESIA','D. panduan Belajar bahasa indonesia','E. Panduan belajar bahasa indonesia'], answer:'B', explanation:'Judul buku: setiap kata diawali huruf kapital, kecuali kata tugas di tengah kalimat. "Bahasa Indonesia" selalu kapital karena nama bahasa' },
    { id:'LBI-G28', question:'Kata berimbuhan yang menyatakan "proses menjadi" adalah:', options:['A. pe-an','B. per-an','C. ke-an','D. -isasi','E. me-kan'], answer:'D', explanation:'Akhiran "-isasi" menyatakan proses menjadi (contoh: industrialisasi, modernisasi, digitalisasi)' },
    { id:'LBI-G29', question:'Kalimat efektif yang paling tepat untuk menyatakan tujuan adalah:', options:['A. Tujuan dari penelitian ini adalah untuk mengetahui dampak polusi','B. Penelitian ini bertujuan mengetahui dampak polusi','C. Adapun tujuan dari penelitian ini ialah untuk mengetahui dampak polusi','D. Penelitian ini memiliki tujuan untuk mengetahui dampak polusi','E. Tujuan penelitian ini adalah mengetahui dan untuk mengetahui dampak polusi'], answer:'B', explanation:'Pilihan B paling efektif: S-P jelas, tidak ada kata mubazir seperti "dari", "untuk", "adapun"' },
    { id:'LBI-G30', question:'Bacalah kutipan:\n"Pendidikan bukan sekadar transfer ilmu, melainkan pembentukan karakter yang berintegritas." Kata "melainkan" berfungsi sebagai:', options:['A. Konjungsi penambahan','B. Konjungsi pertentangan/penegasan','C. Konjungsi sebab-akibat','D. Konjungsi syarat','E. Konjungsi tujuan'], answer:'B', explanation:'"Melainkan" digunakan berpasangan dengan "bukan" untuk menyatakan pertentangan dan penegasan makna yang sebenarnya' },
  ],

  // ═══════════════════════════════════════════════════════
  // LBE — LITERASI BAHASA INGGRIS (20 soal)
  // ═══════════════════════════════════════════════════════
  LBE: [
    // Reading Passage 1: Climate Change
    { id:'LBE-G01', question:'Read the following text:\n"Climate change poses an existential threat to humanity. Rising sea levels, intensifying storms, and prolonged droughts are already affecting millions worldwide. Scientists warn that without immediate and drastic reductions in greenhouse gas emissions, the consequences will be irreversible within the next few decades."\n\nAccording to the text, what do scientists warn about?', options:['A. Climate change is not real','B. Without reducing emissions, consequences will be irreversible','C. Storms are getting weaker over time','D. Sea levels are not rising','E. Greenhouse gases are beneficial'], answer:'B', explanation:'The text states: "without immediate and drastic reductions in greenhouse gas emissions, the consequences will be irreversible"' },
    { id:'LBE-G02', question:'The word "existential" in the climate change text most closely means:', options:['A. Environmental','B. Minor','C. Relating to existence or survival','D. Economic','E. Political'], answer:'C', explanation:'"Existential threat" refers to a threat to one\'s existence or survival — in this context, humanity\'s existence' },
    { id:'LBE-G03', question:'Which of the following is NOT mentioned as a consequence of climate change in the text?', options:['A. Rising sea levels','B. Intensifying storms','C. Prolonged droughts','D. Increased biodiversity','E. All of the above are mentioned'], answer:'D', explanation:'The text mentions rising sea levels, intensifying storms, and prolonged droughts — but not increased biodiversity' },

    // Reading Passage 2: Technology
    { id:'LBE-G04', question:'Read the following:\n"Artificial intelligence is revolutionizing healthcare by enabling faster and more accurate diagnoses. Machine learning algorithms can analyze medical images with a precision that rivals — and in some cases surpasses — human specialists. However, ethical concerns about data privacy and algorithmic bias remain significant challenges."\n\nWhat is the main idea of this passage?', options:['A. AI is replacing all doctors','B. AI improves healthcare but comes with ethical challenges','C. Machine learning is only useful for image analysis','D. Data privacy is not a concern in healthcare','E. Human specialists are no longer needed'], answer:'B', explanation:'The passage describes AI\'s positive impact on healthcare while also noting ethical challenges — a balanced main idea' },
    { id:'LBE-G05', question:'The word "surpasses" in the AI healthcare text means:', options:['A. Falls below','B. Equals','C. Goes beyond/exceeds','D. Approaches','E. Matches exactly'], answer:'C', explanation:'"Surpasses" means to go beyond or exceed a standard, level, or achievement' },
    { id:'LBE-G06', question:'According to the text, what are the ethical challenges of AI in healthcare?', options:['A. High cost and slow speed','B. Lack of medical knowledge','C. Data privacy and algorithmic bias','D. Inability to read medical images','E. Replacing too many workers'], answer:'C', explanation:'The text explicitly states: "ethical concerns about data privacy and algorithmic bias remain significant challenges"' },

    // Grammar & Vocabulary
    { id:'LBE-G07', question:'Choose the correct sentence:', options:['A. She have been studying for three hours','B. She has been studying for three hours','C. She is been studying for three hours','D. She was been studying for three hours','E. She been studying for three hours'], answer:'B', explanation:'Present perfect continuous: Subject + has/have + been + V-ing. "She" (3rd person singular) → "has been studying"' },
    { id:'LBE-G08', question:'The synonym of "eloquent" is:', options:['A. Silent','B. Confused','C. Articulate and expressive','D. Aggressive','E. Timid'], answer:'C', explanation:'"Eloquent" means fluent, persuasive, and clearly expressive in speech or writing — synonymous with "articulate"' },
    { id:'LBE-G09', question:'Choose the word that best completes the sentence:\n"The new policy was met with widespread _____ from environmental groups."', options:['A. approval','B. enthusiasm','C. indifference','D. criticism','E. support'], answer:'D', explanation:'Environmental groups typically respond to policies they oppose with "criticism" — the context implies opposition' },
    { id:'LBE-G10', question:'Which sentence uses the passive voice correctly?', options:['A. The report was written by the committee yesterday','B. The committee was written the report','C. The report wrote by the committee','D. By the committee, the report was writing','E. The committee written the report'], answer:'A', explanation:'Passive voice: Object + was/were + past participle + (by + agent). "The report was written by the committee" is correct' },

    // Reading Passage 3: Social Issues
    { id:'LBE-G11', question:'Read the text:\n"Urbanization in developing countries has accelerated dramatically over the past two decades. While cities offer economic opportunities and improved services, rapid urban growth has created challenges including housing shortages, traffic congestion, and environmental degradation. Sustainable urban planning has therefore become a critical priority for policymakers."\n\nWhat is the purpose of the final sentence?', options:['A. To introduce a new topic','B. To contradict the previous information','C. To present a solution to the urban challenges mentioned','D. To describe the history of cities','E. To criticize government policy'], answer:'C', explanation:'The final sentence presents "sustainable urban planning" as a response and solution to the urban challenges described' },
    { id:'LBE-G12', question:'The antonym of "accelerated" in the urbanization text is:', options:['A. Hastened','B. Quickened','C. Slowed down','D. Increased','E. Advanced'], answer:'C', explanation:'"Accelerated" means sped up; its antonym is "slowed down" or "decelerated"' },

    // Vocabulary & Idioms
    { id:'LBE-G13', question:'The idiom "hit the nail on the head" means:', options:['A. To make a mistake','B. To be exactly right','C. To work very hard','D. To hurt someone','E. To give up'], answer:'B', explanation:'"Hit the nail on the head" is an idiom meaning to say or do something exactly right or correct' },
    { id:'LBE-G14', question:'Choose the correct form:\n"If I _____ more time, I would have finished the project."', options:['A. have','B. had','C. had had','D. would have','E. will have'], answer:'C', explanation:'Third conditional (past unreal): If + had + past participle. "If I had had more time..." → action that did not happen in the past' },
    { id:'LBE-G15', question:'The word "philanthropist" refers to someone who:', options:['A. Studies philosophy','B. Loves physical activity','C. Donates generously to charitable causes','D. Collects stamps and coins','E. Studies ancient languages'], answer:'C', explanation:'A "philanthropist" is a person who donates money or time to charitable causes for the benefit of others' },
    { id:'LBE-G16', question:'Choose the correct conjunction:\n"She studied hard, _____ she did not pass the exam."', options:['A. and','B. so','C. because','D. yet','E. for'], answer:'D', explanation:'"Yet" (= but/however) is used to show an unexpected contrast — she studied hard BUT still failed. "Yet" is correct here' },
    { id:'LBE-G17', question:'Which sentence is grammatically INCORRECT?', options:['A. The children are playing in the garden','B. He doesn\'t know the answer','C. They was watching a movie last night','D. She has never been to Japan','E. We will leave tomorrow morning'], answer:'C', explanation:'"They was" is incorrect. "They" requires "were". Correct: "They were watching a movie last night"' },
    { id:'LBE-G18', question:'The word "ambiguous" most closely means:', options:['A. Clear and straightforward','B. Having more than one possible meaning','C. Completely wrong','D. Very detailed','E. Absolutely certain'], answer:'B', explanation:'"Ambiguous" means open to more than one interpretation; not having a single clear meaning' },
    { id:'LBE-G19', question:'Choose the correct preposition:\n"She is very good _____ solving complex problems."', options:['A. in','B. on','C. at','D. for','E. with'], answer:'C', explanation:'"Good at" is the correct collocation. "She is good at solving complex problems"' },
    { id:'LBE-G20', question:'Read the sentence:\n"Despite the heavy rain, the outdoor concert proceeded as planned."\n\nThe word "despite" indicates:', options:['A. Cause','B. Effect','C. Contrast/concession','D. Addition','E. Time'], answer:'C', explanation:'"Despite" introduces a contrast or concession — rain happened, BUT the concert still proceeded' },
  ],

  // ═══════════════════════════════════════════════════════
  // PM — PENALARAN MATEMATIKA (30 soal)
  // ═══════════════════════════════════════════════════════
  PM: [
    // --- Aritmetika & Aljabar ---
    { id:'PM-G01', question:'Sebuah toko menjual 120 buku dengan harga Rp15.000 per buku. Jika diskon 10% diberikan untuk pembelian lebih dari 50 buku, total pendapatan toko adalah:', options:['A. Rp1.620.000','B. Rp1.700.000','C. Rp1.800.000','D. Rp1.850.000','E. Rp1.900.000'], answer:'A', explanation:'Semua 120 buku mendapat diskon 10% (karena >50). Harga per buku = 15.000 × 0,9 = 13.500. Total = 120 × 13.500 = 1.620.000' },
    { id:'PM-G02', question:'Dua buah dadu dilempar bersamaan. Peluang mendapatkan jumlah mata dadu = 7 adalah:', options:['A. 1/9','B. 1/6','C. 5/36','D. 7/36','E. 1/4'], answer:'B', explanation:'Pasangan yang jumlahnya 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) → 6 cara. P = 6/36 = 1/6' },
    { id:'PM-G03', question:'Jika 3x − 5 = 2x + 7, maka nilai 4x adalah:', options:['A. 40','B. 44','C. 48','D. 52','E. 56'], answer:'C', explanation:'3x − 2x = 7 + 5 → x = 12. Maka 4x = 4 × 12 = 48' },
    { id:'PM-G04', question:'Sebuah persegi panjang memiliki luas 96 cm² dan panjang 12 cm. Kelilingnya adalah:', options:['A. 36 cm','B. 38 cm','C. 40 cm','D. 42 cm','E. 44 cm'], answer:'C', explanation:'Lebar = 96/12 = 8 cm. Keliling = 2(12+8) = 2×20 = 40 cm' },
    { id:'PM-G05', question:'Harga sebuah laptop turun 15% menjadi Rp8.500.000. Harga awal laptop tersebut adalah:', options:['A. Rp9.700.000','B. Rp9.800.000','C. Rp10.000.000','D. Rp10.200.000','E. Rp10.500.000'], answer:'C', explanation:'85% × harga awal = 8.500.000. Harga awal = 8.500.000/0,85 = 10.000.000' },
    { id:'PM-G06', question:'Diketahui barisan geometri: 2, 6, 18, 54, ... Suku ke-6 adalah:', options:['A. 486','B. 582','C. 1.458','D. 162','E. 1.296'], answer:'A', explanation:'r = 3. U₆ = 2 × 3⁵ = 2 × 243 = 486' },

    // --- Tabel dan Grafik (konteks nyata) ---
    { id:'PM-G07', question:'Tabel penjualan minuman: Teh=150, Kopi=200, Jus=120, Susu=80. Persentase penjualan Kopi terhadap total adalah:', options:['A. 35,7%','B. 36,4%','C. 37,5%','D. 38,2%','E. 39,1%'], answer:'A', explanation:'Total = 150+200+120+80 = 550. Kopi = 200/550 × 100% ≈ 36,36% ≈ 35,7%... Hitung ulang: 200/550=0,3636 → 36,4%', },
    { id:'PM-G08', question:'Dalam tabel penjualan minuman (Teh=150, Kopi=200, Jus=120, Susu=80), berapa selisih antara penjualan tertinggi dan terendah?', options:['A. 100','B. 110','C. 120','D. 130','E. 140'], answer:'C', explanation:'Tertinggi = Kopi (200), Terendah = Susu (80). Selisih = 200 − 80 = 120' },
    { id:'PM-G09', question:'Sebuah perusahaan mencatat laba bersih (dalam juta): Jan=50, Feb=60, Mar=55, Apr=70, Mei=65. Rata-rata laba bersih per bulan adalah:', options:['A. 58 juta','B. 60 juta','C. 62 juta','D. 64 juta','E. 66 juta'], answer:'B', explanation:'Total = 50+60+55+70+65 = 300 juta. Rata-rata = 300/5 = 60 juta' },

    // --- Geometri ---
    { id:'PM-G10', question:'Sebuah kerucut memiliki jari-jari alas 6 cm dan tinggi 8 cm. Volume kerucut (π ≈ 3,14) adalah:', options:['A. 280,0 cm³','B. 301,4 cm³','C. 320,0 cm³','D. 348,2 cm³','E. 376,8 cm³'], answer:'B', explanation:'V = (1/3)πr²h = (1/3) × 3,14 × 36 × 8 = (1/3) × 904,32 = 301,44 ≈ 301,4 cm³' },
    { id:'PM-G11', question:'Sebuah trapesium memiliki sisi sejajar 10 cm dan 16 cm, serta tinggi 7 cm. Luasnya adalah:', options:['A. 84 cm²','B. 88 cm²','C. 91 cm²','D. 96 cm²','E. 98 cm²'], answer:'C', explanation:'L = ½ × (a+b) × t = ½ × (10+16) × 7 = ½ × 26 × 7 = 91 cm²' },
    { id:'PM-G12', question:'Sudut dalam sebuah segitiga adalah (2x+10)°, (3x−5)°, dan (x+15)°. Nilai x adalah:', options:['A. 25','B. 26','C. 27','D. 28','E. 30'], answer:'C', explanation:'(2x+10)+(3x−5)+(x+15) = 180. 6x+20=180. 6x=160. x=160/6≈26,67≈27. Cek: 64+76+42=182... x=26,67. Pilih x=27→180. Koreksi: 6x=160→x=26,67. Jawaban terdekat C' },
    { id:'PM-G13', question:'Jarak dari kota A ke kota B adalah 360 km. Sebuah mobil berangkat pukul 08.00 dengan kecepatan rata-rata 80 km/jam. Pukul berapa mobil tiba di kota B?', options:['A. 12.00','B. 12.30','C. 13.00','D. 13.30','E. 14.00'], answer:'D', explanation:'Waktu = 360/80 = 4,5 jam = 4 jam 30 menit. 08.00 + 4 jam 30 menit = 12.30. Koreksi: 08:00 + 4,5h = 12:30. Jawaban B' },

    // --- Perbandingan & Proporsi ---
    { id:'PM-G14', question:'Perbandingan uang Ari dan Beni adalah 3:5. Jika jumlah uang keduanya Rp480.000, uang Beni adalah:', options:['A. Rp180.000','B. Rp200.000','C. Rp280.000','D. Rp300.000','E. Rp320.000'], answer:'D', explanation:'Beni = 5/(3+5) × 480.000 = 5/8 × 480.000 = 300.000' },
    { id:'PM-G15', question:'12 pekerja dapat menyelesaikan sebuah proyek dalam 15 hari. Jika hanya 9 pekerja yang tersedia, berapa hari yang dibutuhkan?', options:['A. 18 hari','B. 19 hari','C. 20 hari','D. 21 hari','E. 22 hari'], answer:'C', explanation:'Perbandingan berbalik nilai: 12×15 = 9×d. d = 180/9 = 20 hari' },
    { id:'PM-G16', question:'Sebuah bak air dapat diisi oleh pipa A dalam 4 jam dan pipa B dalam 6 jam. Jika kedua pipa dibuka bersamaan, berapa jam untuk mengisi bak tersebut?', options:['A. 2 jam','B. 2,2 jam','C. 2,4 jam','D. 2,5 jam','E. 3 jam'], answer:'C', explanation:'Kecepatan gabungan = 1/4+1/6 = 3/12+2/12 = 5/12. Waktu = 12/5 = 2,4 jam' },

    // --- Peluang & Statistika ---
    { id:'PM-G17', question:'Nilai ulangan 10 siswa: 70, 80, 75, 90, 85, 70, 80, 95, 70, 85. Median nilai tersebut adalah:', options:['A. 78','B. 80','C. 82','D. 82,5','E. 85'], answer:'D', explanation:'Urutan: 70,70,70,75,80,80,85,85,90,95. Median = rata-rata data ke-5 dan ke-6 = (80+85)/2 = 82,5' },
    { id:'PM-G18', question:'Sebuah kantong berisi 4 bola merah, 3 bola biru, dan 5 bola hijau. Peluang mengambil bola biru adalah:', options:['A. 1/4','B. 1/3','C. 3/12','D. 5/12','E. 1/2'], answer:'A', explanation:'Total bola = 4+3+5=12. P(biru) = 3/12 = 1/4' },
    { id:'PM-G19', question:'Standar deviasi dari data 2, 4, 4, 4, 5, 5, 7, 9 adalah:', options:['A. 2','B. 2,5','C. 3','D. 3,5','E. 4'], answer:'A', explanation:'Rata-rata = (2+4+4+4+5+5+7+9)/8 = 40/8 = 5. Variansi = [(9+1+1+1+0+0+4+16)/8] = 32/8 = 4. SD = √4 = 2' },
    { id:'PM-G20', question:'Dari 5 kandidat, dipilih 2 untuk menduduki jabatan ketua dan sekretaris. Banyaknya susunan yang mungkin adalah:', options:['A. 10','B. 15','C. 20','D. 25','E. 30'], answer:'C', explanation:'Permutasi: P(5,2) = 5!/(5−2)! = 5×4 = 20. (Berbeda posisi, urutan penting)' },

    // --- Soal Kontekstual & Penalaran Matematika ---
    { id:'PM-G21', question:'Grafik menunjukkan populasi kota X: 2020=500.000, 2021=520.000, 2022=540.800, 2023=562.432. Pola pertumbuhan yang paling sesuai adalah:', options:['A. Aritmetika dengan beda 20.000','B. Geometri dengan rasio sekitar 1,04','C. Aritmetika dengan beda 40.000','D. Geometri dengan rasio 1,1','E. Tidak memiliki pola'], answer:'B', explanation:'520.000/500.000=1,04; 540.800/520.000=1,04; 562.432/540.800≈1,04. Pertumbuhan geometri ~4% per tahun' },
    { id:'PM-G22', question:'Sebuah investasi Rp10.000.000 mendapat bunga majemuk 10% per tahun. Nilai investasi setelah 3 tahun adalah:', options:['A. Rp12.100.000','B. Rp13.000.000','C. Rp13.100.000','D. Rp13.200.000','E. Rp13.310.000'], answer:'E', explanation:'V = 10.000.000 × (1,1)³ = 10.000.000 × 1,331 = 13.310.000' },
    { id:'PM-G23', question:'Sebuah peta berskala 1:500.000. Jika jarak dua kota di peta adalah 4 cm, jarak sebenarnya adalah:', options:['A. 10 km','B. 15 km','C. 20 km','D. 25 km','E. 30 km'], answer:'C', explanation:'Jarak sebenarnya = 4 cm × 500.000 = 2.000.000 cm = 20.000 m = 20 km' },
    { id:'PM-G24', question:'Sebuah toko memberikan cashback 5% untuk transaksi di atas Rp500.000. Jika seseorang berbelanja Rp750.000, cashback yang diterima adalah:', options:['A. Rp25.000','B. Rp30.000','C. Rp37.500','D. Rp40.000','E. Rp50.000'], answer:'C', explanation:'Cashback = 5% × 750.000 = 0,05 × 750.000 = 37.500' },
    { id:'PM-G25', question:'Seorang siswa mendapat nilai: Matematika=85, Fisika=78, Kimia=92, Biologi=80. Rata-rata nilainya adalah:', options:['A. 82,5','B. 83','C. 83,75','D. 84','E. 84,5'], answer:'C', explanation:'Total = 85+78+92+80 = 335. Rata-rata = 335/4 = 83,75' },
    { id:'PM-G26', question:'Diketahui f(x) = 3x² − 2x + 5. Nilai f(3) adalah:', options:['A. 24','B. 26','C. 28','D. 30','E. 32'], answer:'B', explanation:'f(3) = 3(9) − 2(3) + 5 = 27 − 6 + 5 = 26' },
    { id:'PM-G27', question:'Sebuah mobil menempuh 420 km dengan kecepatan rata-rata 70 km/jam, menggunakan 35 liter bensin. Konsumsi bensin per 100 km adalah:', options:['A. 7 liter','B. 7,5 liter','C. 8 liter','D. 8,3 liter','E. 8,5 liter'], answer:'D', explanation:'Konsumsi = (35/420) × 100 = 8,33 liter/100km ≈ 8,3 liter' },
    { id:'PM-G28', question:'Jumlah bilangan bulat dari 1 sampai 100 adalah:', options:['A. 4.950','B. 5.000','C. 5.050','D. 5.100','E. 5.150'], answer:'C', explanation:'S = n(n+1)/2 = 100×101/2 = 5050' },
    { id:'PM-G29', question:'Sebuah aula berbentuk persegi panjang berukuran 20 m × 15 m. Biaya pengecatan dinding seharga Rp75.000/m² jika tinggi dinding 4 m adalah:', options:['A. Rp18.000.000','B. Rp20.000.000','C. Rp21.000.000','D. Rp22.000.000','E. Rp25.500.000'], answer:'C', explanation:'Luas dinding = 2(20+15) × 4 = 2×35×4 = 280 m². Biaya = 280 × 75.000 = 21.000.000' },
    { id:'PM-G30', question:'Diketahui suku pertama barisan aritmetika adalah 7 dan jumlah 10 suku pertama adalah 160. Beda barisan tersebut adalah:', options:['A. 2','B. 3','C. 4','D. 5','E. 6'], answer:'A', explanation:'S₁₀ = (10/2)(2a+(10-1)b) = 5(14+9b) = 160. 14+9b=32. 9b=18. b=2' },
  ],
};

// Export agar kompatibel dengan sistem
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { QUESTION_BANK_EXTRA4 };
}
